Repository OneCommunityGlobal/HGNRest, pull requests merged in 2023-11, with the labels that each got.

#590 Tim add bm projects summary routing
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/bmdashboard/bmProjectController.js
  src/models/bmdashboard/buildingProject.js
  src/models/inventoryItemMaterial.js
  src/routes/bmdashboard/bmMaterialsRouter.js
  src/routes/bmdashboard/bmProjectRouter.js
  src/startup/routes.js
Labels: Do Not Review

#562 Roberto-Fixes assign badge delay
  src/controllers/badgeController.js
Labels: Moved to Final Review

#485 Shivansh made Custom Infringement email for Core Team
  src/helpers/userHelper.js
Labels: High Priority - Please Review

#621 Hotfix: Carl-Suggestion-Email-Improvement
  src/controllers/dashBoardController.js
Labels: Do Not Review

#622 Hotfix: Carl blue square replyTo
  src/controllers/dashBoardController.js
  src/helpers/userHelper.js
Labels: Do Not Review
