Repository OneCommunityGlobal/HGNRest, pull requests merged in 2023-12, with the labels that each got.

#571 Leo_fix_issue_update_with_updating_existing_password
  src/controllers/userProfileController.js
Labels: Moved to Final Review

#618 Tim update bm project api
  src/controllers/bmdashboard/bmProjectController.js
  src/models/bmdashboard/buildingProject.js
Labels: Do Not Review

#642 Shengwei fixed no badge earned date issue
  src/controllers/badgeController.js
  src/helpers/userHelper.js
Labels: High Priority - Please Review

#653 Tim add building reusable schema
  src/models/bmdashboard/buildingInventoryItem.js
Labels: Do Not Review

#657 Carl- Hotfix- added the replyTo feature
  src/controllers/timeEntryController.js
  src/helpers/userHelper.js
Labels: Do Not Review

#611 yihan Create way to manually add in lost hours for past years of volunteers
  src/controllers/timeEntryController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/timeentry.js
  src/routes/timeentryRouter.js
Labels: High Priority - Please Review
