Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-06, with the labels that each got.

#964 Ilya log tool backend
  src/controllers/bmdashboard/bmInventoryTypeController.js
  src/controllers/bmdashboard/bmToolController.js
  src/models/bmdashboard/buildingInventoryItem.js
  src/models/bmdashboard/buildingInventoryType.js
  src/routes/bmdashboard/bmToolRouter.js
  src/startup/routes.js
Labels: High Priority - Please Review First

#947 Summit New personal max Record Award
  src/helpers/userHelper.js
Labels: High Priority - Please Review First

#948 Peterson_fix_the_bug_after_writing_find_user_in_the_input_and_receivi…
  src/controllers/userProfileController.js
Labels: Moved to Final Review

#979 Ramakrishna Updating the teamcode validation with numbers
  src/models/team.js
  src/models/userProfile.js
Labels: High Priority - Please Review First

#989 Abdel modal assign blue square emails
  src/controllers/BlueSquareEmailAssignmentController.js
  src/helpers/userHelper.js
  src/models/BlueSquareEmailAssignment.js
  src/routes/BlueSquareEmailAssignmentRouter.js
  src/startup/routes.js
Labels: Do Not Review

#925 Jordy add notification controller unit tests
  requirements/notificationController/creatUserNotification.md
  requirements/notificationController/deleteUserNotification.md
  requirements/notificationController/getSentNotifications.md
  requirements/notificationController/getUnreadUserNotifications.md
  requirements/notificationController/getUserNotifications.md
  requirements/notificationController/markNotificationAsRead.md
  src/controllers/notificationController.js
  src/controllers/notificationController.spec.js
  src/utilities/htmlContentSanitizer.js
Labels: Moved to Final Review

#927 Anirudh - Fetch end date field from dashboardhelper
  package-lock.json
  src/helpers/dashboardhelper.js
Labels: Moved to Final Review

#953 Imran added getProjectMembers permission
  src/controllers/projectController.js
Labels: High Priority - Please Review First

#942 Imran edit summary submit requirement others
  src/controllers/userProfileController.js
  src/test/createTestPermissions.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#974 Jingyi create/edit/delete badges permission
  src/controllers/badgeController.js
Labels: Moved to Final Review

#963 Shengwei_update_backend_permission_control_for_protected_account
  src/controllers/userProfileController.js
  src/services/userService.js
  src/startup/logger.js
  src/utilities/constants.js
  src/utilities/nodeCache.js
  src/utilities/objectUtils.js
  src/utilities/permission.spec.js
  src/utilities/permissions.js
Labels: High Priority - Please Review First

#819 test: Ensure getUser returns 200, with the requestor body
  requirements/logincontroller/getUser-usecase.md
  src/controllers/logincontroller.spec.js
  src/test/assertions.js
  src/test/index.js
Labels: Do Not Review

#924 Nathan separate edit time entry permissions
  src/controllers/timeEntryController.js
  src/test/createTestPermissions.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First
