Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-05, with the labels that each got.

#829 Ivy-blue-email-add-administrative-details
  src/controllers/timeEntryController.js
  src/controllers/userProfileController.js
  src/helpers/userHelper.js
Labels: High Priority - Please Review First

#781 Peterson_Fix_the_500_error_in_editing_last_week
  src/routes/userProfileRouter.js
Labels: Moved to Final Review

#596 Luis fix user profile projects delay
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/dashBoardController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/projectController.js
  src/controllers/rolePresetsController.js
  src/controllers/rolesController.js
  src/controllers/userProfileController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/userProfile.js
  src/routes/profileInitialSetupRouter.js
Labels: Do Not Review

#839 Nathan seeUsersInDashboard Permission
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#821 Yaohong create Quick Setup Modal for new team members
  src/controllers/titleController.js
  src/models/title.js
  src/routes/titleRouter.js
  src/startup/routes.js
  src/utilities/createInitialPermissions.js
Labels: Moved to Final Review

#767 Shengwei create setup history modal
  src/controllers/profileInitialSetupController.js
  src/helpers/userHelper.js
  src/models/profileInitialSetupToken.js
  src/routes/profileInitialSetupRouter.js
Labels: High Priority - Please Review First

#944 Jordy fix es6export syntax
  package-lock.json
  src/constants/message.js
  src/utilities/htmlContentSanitizer.js
  src/utilities/timeUtils.js
  src/websockets/TimerService/clientsHandler.js
Labels: High Priority - Please Review First

#955 chris fix show total project/people/team reports
  src/controllers/timeEntryController.js
  src/routes/timeentryRouter.js
Labels: High Priority - Please Review First

#913 Ilya - Tools table
  package-lock.json
  src/controllers/bmdashboard/bmToolController.js
  src/helpers/userHelper.js
  src/models/bmdashboard/buildingInventoryItem.js
  src/models/bmdashboard/buildingInventoryType.js
  src/routes/bmdashboard/bmToolRouter.js
Labels: High Priority - Please Review First

#916 Imran add check for manageAdminLink Permission
  src/controllers/userProfileController.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#740 Equipment_List_View
  src/controllers/bmdashboard/bmEquipmentController.js
  src/routes/bmdashboard/bmEquipmentsRouter.js
  src/startup/routes.js
Labels: Moved to Final Review
