Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-04, with the labels that each got.

#825 Abi badge controller post method tests
  requirements/badgeController/postBadge.md
  src/controllers/badgeController.js
  src/controllers/badgeController.spec.js
  src/routes/badgeRouter.test.js
  src/test/db/createRole.js
  src/test/index.js
Labels: High Priority - Please Review First

#834 Diego - build: updated husky preparation script for macos and linux users
  package.json
Labels: hotfix, High Priority - Please Review First

#838 Troubleshoot by Ramya and Jae
  .eslintignore
  .eslintrc
  .husky/pre-commit
  .lintstagedrc.json
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
  troubleshoot.js
Labels: Do Not Review

#863 build: updated .babelrc to exclude test files at build time
  .babelrc
Labels: High Priority - Please Review First

#569 Roberto - For Dev Branch- Adds email notification for Owner create/reset password
  src/controllers/userProfileController.js
Labels: Moved to Final Review

#862 Abi assign badge tests
  requirements/badgeController/assignBadges.md
  requirements/badgeController/getAllABadges.md
  src/controllers/badgeController.js
  src/controllers/badgeController.spec.js
  src/routes/badgeRouter.test.js
  src/test/mock-request.js
Labels: Do Not Review

#861 Adds user's ability to check entered password to reveal the weeklySummaryRecipient
  package-lock.json
  src/controllers/userProfileController.js
Labels: Do Not Review, High Priority - Please Review First

#789 Jingyi-User Profile: Rehireable / Notrehireable Check Box
  package-lock.json
  src/controllers/userProfileController.js
  src/models/userProfile.js
  src/routes/userProfileRouter.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#881 XiaoW_Refactor of timeentry controllers and fix the edit history issue
  .gitignore
  src/controllers/timeEntryController.js
  src/routes/timeentryRouter.js
Labels: High Priority - Please Review First

#419 Abdel deadline follow up tracking solution
  src/controllers/followUpController.js
  src/controllers/taskController.js
  src/controllers/userProfileController.js
  src/models/followUp.js
  src/routes/followUpRouter.js
  src/startup/routes.js
Labels: Moved to Final Review

#900 Shengwei_eliminate_sentry_error_and_update_sentry_log_plugin
  package-lock.json
  package.json
  src/controllers/teamController.js
  src/helpers/userHelper.js
  src/server.js
  src/startup/logger.js
  src/utilities/emailSender.js
Labels: High Priority - Please Review First

#802 Xiao fix x hours in one week badges
  src/helpers/userHelper.js
  src/routes/badgeRouter.js
Labels: High Priority - Please Review First

#780 Ilya - Consumables: Single Update
  src/controllers/badgeController.js
  src/controllers/bmdashboard/bmConsumableController.js
  src/controllers/bmdashboard/bmInventoryTypeController.js
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/bmdashboard/bmNewLessonController.js
  src/controllers/bmdashboard/bmProjectController.js
  src/controllers/bmdashboard/bmToolController.js
  src/controllers/dashBoardController.js
  src/controllers/informationController.js
  src/controllers/inventoryController.js
  src/controllers/mapLocationsController.js
  src/controllers/mouseoverTextController.js
  src/controllers/popupEditorBackupController.js
  src/controllers/popupEditorController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/reportsController.js
  src/controllers/rolePresetsController.js
  src/controllers/rolesController.js
  src/controllers/taskController.js
  src/controllers/taskNotificationController.js
  src/controllers/userProfileController.js
  src/controllers/wbsController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/userProfile.js
  src/routes/bmdashboard/bmConsumablesRouter.js
  src/routes/userProfileRouter.js
  src/startup/db.js
  src/utilities/addMembersToTeams.js
  src/utilities/addNewField.js
  src/utilities/yearMonthDayDateValidator.js
  src/websockets/TimerService/connectionsHandler.js
Labels: High Priority - Please Review First

#795 Shengwei add stop blue sqaure added to new user
  package-lock.json
  package.json
  src/constants/eventTypes.js
  src/constants/message.js
  src/controllers/actionItemController.js
  src/controllers/notificationController.js
  src/controllers/timeEntryController.js
  src/controllers/userProfileController.js
  src/helpers/notificationhelper.js
  src/helpers/userHelper.js
  src/models/notification.js
  src/models/userProfile.js
  src/routes/actionItemRouter.js
  src/routes/notificationRouter.js
  src/services/notificationService.js
  src/startup/routes.js
  src/utilities/htmlContentSanitizer.js
  src/utilities/timeUtils.js
Labels: High Priority - Please Review First
