Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-02, with the labels that each got.

#693 Sucheta - Update Projects Page sorting
  src/controllers/projectController.js
  src/controllers/taskController.js
  src/controllers/wbsController.js
Labels: High Priority - Please Review

#640 Jiyuan added scheduled-on date to scheduled blue square reason
  src/models/userProfile.js
Labels: High Priority - Please Review

#673 Yubo- Add core team blue square email template
  src/helpers/userHelper.js
Labels: High Priority - Please Review

#718 Luis warning component backend
  package-lock.json
  src/controllers/badgeController.js
  src/controllers/dashBoardController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/userProfileController.js
  src/controllers/warningsController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/userProfile.js
  src/routes/profileInitialSetupRouter.js
  src/routes/warningRouter.js
  src/startup/routes.js
Labels: Moved to Final Review

#649 Shengwei fix jae account update permission issue
  src/controllers/badgeController.js
  src/models/userProfile.js
  src/utilities/exceptionHandler.js
Labels: High Priority - Please Review First

#749 Yubo- fix blue square email typo
  src/helpers/userHelper.js
Labels: Do Not Review

#703 Shengwei Enhancement: badge assignment and modification will not remove earned date
  src/controllers/badgeController.js
  src/helpers/userHelper.js
  src/models/userProfile.js
Labels: Moved to Final Review

#639 Roberto -adds opencage http request to backend timezone route
  package-lock.json
  src/controllers/timeZoneAPIController.js
  src/routes/timeZoneAPIRoutes.js
  src/startup/middleware.js
Labels: Moved to Final Review

#755 rhea latest commit on issue backend
  src/controllers/bmdashboard/bmIssueController.js
  src/models/bmdashboard/buildingIssue.js
  src/routes/bmdashboard/bmIssueRouter.js
  src/startup/routes.js
Labels: Do Not Review
