Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-01, with the labels that each got.

#668 Xiaow TimeEntryForm refactor (backend)
  src/controllers/taskController.js
  src/controllers/timeEntryController.js
  src/controllers/wbsController.js
  src/helpers/helperModels/userProjects.js
  src/models/timeentry.js
  src/models/userProfile.js
  src/routes/taskRouter.js
  src/routes/wbsRouter.js
Labels: High Priority - Please Review

#679 Vishala Leaderboard api and Task api fix
  src/controllers/taskController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
Labels: High Priority - Please Review

#683 Hot-fix-Carl-Review-Request-CC-Bug
  src/controllers/taskController.js
Labels: Do Not Review

#603 Xiao F Create way for owner to edit & update ChatGPT prompt text
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/dashBoardController.js
  src/controllers/mapLocationsController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/reasonSchedulingController.js
  src/controllers/taskController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/models/mapLocation.js
  src/models/weeklySummaryAIPrompt.js
  src/routes/bmdashboard/bmMaterialsRouter.js
  src/routes/dashboardRouter.js
  src/routes/mapLocationsRouter.js
  src/routes/profileInitialSetupRouter.js
  src/startup/routes.js
  src/utilities/emailSender.js
Labels: High Priority - Please Review

#699 XiaoW_Refactor time entry handlers and fix bugs
  src/controllers/taskController.js
  src/controllers/timeEntryController.js
  src/controllers/userProfileController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/timeEntryHelper.js
  src/models/timeentry.js
Labels: High Priority - Please Review

#613 Rhea create newLessom routes and controller
  src/controllers/bmdashboard/bmNewLessonController.js
  src/models/bmdashboard/buildingNewLesson.js
  src/routes/bmdashboard/bmNewLessonRouter.js
  src/startup/routes.js
Labels: Do Not Review

#530 Jerry - Track Who Changes Permissions On Permissions Management Page
  src/controllers/permissionChangeLogsController.js
  src/models/permissionChangeLog.js
  src/routes/permissionChangeLogsRouter.js
  src/routes/roleRouter.js
  src/startup/routes.js
  src/utilities/logPermissionChangeByAccount.js
Labels: Moved to Final Review

#696 Add link to submit review
  src/models/task.js
Labels: High Priority - Please Review

#619 Bailey new personal max backend
  src/helpers/userHelper.js
Labels: High Priority - Please Review
