Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-07, with the labels that each got.

#977 Jiayu Fix bug manual add lost volunteer time
  src/controllers/timeEntryController.js
Labels: High Priority - Please Review First

#1019 Ivy-add-blue-square-template
  src/controllers/timeEntryController.js
  src/helpers/userHelper.js
Labels: Do Not Review

#1015 Carlos new pie chart hour visualization by team member project reports
  package-lock.json
  src/controllers/timeEntryController.js
Labels: High Priority - Please Review First

#1010 Ramakrishna Teamcode Regex change and select All with No Team code option fix
  src/models/team.js
  src/models/userProfile.js
Labels: High Priority - Please Review First

#1022 Blue square fringe case fix
  src/helpers/userHelper.js
Labels: Do Not Review

#992 Shereen - Equipment List View
  src/controllers/bmdashboard/bmEquipmentController.js
  src/routes/bmdashboard/bmEquipmentRouter.js
Labels: High Priority - Please Review First

#970 Shereen_Created Routing and controller function for Add Tool
  package-lock.json
  src/controllers/bmdashboard/bmInventoryTypeController.js
  src/models/bmdashboard/buildingInventoryType.js
  src/routes/bmdashboard/bmInventoryTypeRouter.js
Labels: High Priority - Please Review First

#1005 Shereen_Bulk Reusables Update
  src/controllers/bmdashboard/bmReusableController.js
  src/routes/bmdashboard/bmReusableRouter.js
Labels: High Priority - Please Review First

#1017 Jiayu limit see all
  src/controllers/teamController.js
  src/helpers/dashboardhelper.js
  src/models/team.js
  src/routes/teamRouter.js
  src/utilities/addMembersToTeams.js
Labels: High Priority - Please Review First

#908 Shengwei fix Sentry errors and update global error handling
  README.md
  src/app.js
  src/controllers/profileInitialSetupController.js
  src/helpers/userHelper.js
  src/routes/userProfileRouter.js
  src/server.js
  src/startup/logger.js
  src/utilities/emailSender.js
  src/utilities/errorHandling/customError.js
  src/utilities/errorHandling/globalErrorHandler.js
  src/utilities/exceptionHandler.js
Labels: High Priority - Please Review First

#1030 XiaoW_Hotfix of timer won't max out 5 hour limit
  src/websockets/TimerService/clientsHandler.js
Labels: High Priority - Please Review First

#962 Parthj unit and integration test forgotpwdcontroller.js
  package-lock.json
  requirements/forgotPwdController/postForgotPwd.md
  src/controllers/forgotPwdcontroller.spec.js
  src/routes/forgotPwdRouter.test.js
  src/test/assertions.js
  src/utilities/htmlContentSanitizer.js
  src/utilities/timeUtils.js
Labels: High Priority - Please Review First

#949 Hoang fix viewing other dashboard
  src/websockets/TimerService/clientsHandler.js
  src/websockets/index.js
Labels: Moved to Final Review

#1035 fix refresh issue
  src/controllers/profileInitialSetupController.js
Labels: Do Not Review

#996 Jiayu fix streak badge not auto dropoff
  src/controllers/badgeController.js
  src/helpers/userHelper.js
  src/routes/badgeRouter.js
Labels: High Priority - Please Review First, Top Priority and Learning Opportunity

#1007 Parthj unit test time off request controller
  requirements/timeOffRequestController/deleteTimeOffRequestById.md
  requirements/timeOffRequestController/getTimeOffRequestById.md
  requirements/timeOffRequestController/getTimeOffRequests.md
  requirements/timeOffRequestController/setTimeOffRequest.md
  requirements/timeOffRequestController/updateTimeOffRequestById.md
  src/controllers/timeOffRequestController.spec.js
Labels: High Priority - Please Review First

#959 Jordy add owner message controller unit tests
  requirements/ownerMessageController/deleteOwnerMessage.md
  requirements/ownerMessageController/getOwnerMessage.md
  requirements/ownerMessageController/updateOwnerMessage.md
  src/controllers/ownerMessageController.spec.js
Labels: Moved to Final Review

#928 Jordy add force pwd controller unit tests
  requirements/forcePwdController/forcePwd.md
  src/controllers/forcePwdController.spec.js
Labels: Moved to Final Review

#1018 Hoang prevent overriding task edit suggestion's approval/rejection
  src/controllers/taskEditSuggestionController.js
Labels: High Priority - Please Review First

#1029 Abdel - Fix the home country option for new users created with auto setup
  src/controllers/mapLocationsController.js
  src/controllers/profileInitialSetupController.js
  src/models/userProfile.js
Labels: Do Not Review
