Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-08, with the labels that each got.

#965 Lin_dashBoardController_unit_testing
  requirements/dashBoardController/dashboarddata.md
  requirements/dashBoardController/editSuggestionOption.md
  requirements/dashBoardController/getAIPrompt.md
  requirements/dashBoardController/getPromptCopiedDate.md
  requirements/dashBoardController/getSuggestionOption.md
  requirements/dashBoardController/leaderboarddata.md
  requirements/dashBoardController/monthlydata.md
  requirements/dashBoardController/orgData.md
  requirements/dashBoardController/sendBugReport.md
  requirements/dashBoardController/sendMakeSuggestion.md
  requirements/dashBoardController/updateAIPrompt.md
  requirements/dashBoardController/updateCopiedPrompt.md
  requirements/dashBoardController/weeklydata.md
  src/controllers/dashBoardController.js
  src/controllers/dashBoardController.spec.js
Labels: High Priority - Please Review First

#1053 Jiadong - Replace Badges Section on Dashboard / badge count APIs
  package-lock.json
  src/controllers/badgeController.js
  src/models/userProfile.js
  src/routes/badgeRouter.js
Labels: High Priority - Please Review First

#1044 Luis unit test inventory controller get all inv in project
  requirements/inventoryController/getAllInvInProject.md
  requirements/inventoryController/getAllInvInProjectWBS.md
  requirements/inventoryController/postInvInProjectWBS.md
  src/controllers/inventoryController.js
  src/controllers/inventoryController.spec.js
Labels: Moved to Final Review

#1067 Backend Release to Main [1.93]
  src/controllers/teamController.js
  src/controllers/timeEntryController.js
  src/controllers/titleController.js
  src/controllers/userProfileController.js
  src/controllers/warningsController.js
  src/models/team.js
  src/models/userProfile.js
  src/routes/teamRouter.js
  src/routes/userProfileRouter.js
Labels: Do Not Review, DO NOT MERGE

#1004 huijie - fix timelog and profile page times don't match
  src/controllers/timeEntryController.js
  src/routes/timeentryRouter.js
Labels: High Priority - Please Review First, Top Priority and Learning Opportunity

#1034 Ramakrishna edit all team code at Once
  src/controllers/userProfileController.js
  src/routes/userProfileRouter.js
Labels: Moved to Final Review

#1084 Ivy-set-final-day-emailTemplate
  src/controllers/userProfileController.js
  src/helpers/userHelper.js
Labels: High Priority - Please Review First

#1024 Diya Changes to return specific error
  src/controllers/userProfileController.js
Labels: High Priority - Please Review First
