Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-03, with the labels that each got.

#779 Abdel update bleu square scheduler
  src/controllers/reasonSchedulingController.js
  src/controllers/timeOffRequestController.js
  src/helpers/userHelper.js
  src/models/reason.js
  src/models/timeOffRequest.js
  src/routes/reasonRouter.js
  src/routes/timeOffRequestRouter.js
  src/startup/routes.js
Labels: Do Not Review

#762 Shuhua - add google doc icon
  src/helpers/taskHelper.js
Labels: High Priority - Please Review First

#775 Sucheta - Create Summary Report Recipient Button
  package-lock.json
  src/controllers/bmdashboard/bmIssueController.js
  src/controllers/reportsController.js
  src/controllers/userProfileController.js
  src/cronjobs/userProfileJobs.js
  src/helpers/reporthelper.js
  src/helpers/userHelper.js
  src/models/bmdashboard/buildingIssue.js
  src/models/userProfile.js
  src/routes/reportsRouter.js
  src/routes/userProfileRouter.js
  src/utilities/createInitialPermissions.js
Labels: Moved to Final Review

#540 write controllers and routes for email component
  src/controllers/emailController.js
  src/routes/emailRouter.js
  src/startup/routes.js
Labels: Do Not Review

#796 Abdel Rebuilding the new blue square scheduler
  src/controllers/actionItemController.js
  src/controllers/badgeController.js
  src/controllers/bmdashboard/bmConsumableController.js
  src/controllers/bmdashboard/bmInventoryTypeController.js
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/bmdashboard/bmNewLessonController.js
  src/controllers/bmdashboard/bmProjectController.js
  src/controllers/bmdashboard/bmToolController.js
  src/controllers/dashBoardController.js
  src/controllers/informationController.js
  src/controllers/inventoryController.js
  src/controllers/mapLocationsController.js
  src/controllers/mouseoverTextController.js
  src/controllers/popupEditorBackupController.js
  src/controllers/popupEditorController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/reasonSchedulingController.js
  src/controllers/reportsController.js
  src/controllers/rolePresetsController.js
  src/controllers/rolesController.js
  src/controllers/taskController.js
  src/controllers/taskNotificationController.js
  src/controllers/teamController.js
  src/controllers/timeEntryController.js
  src/controllers/timeOffRequestController.js
  src/controllers/userProfileController.js
  src/controllers/wbsController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/timeOffRequest.js
  src/models/userProfile.js
  src/routes/timeOffRequestRouter.js
  src/routes/userProfileRouter.js
  src/startup/db.js
  src/startup/routes.js
  src/utilities/addMembersToTeams.js
  src/utilities/addNewField.js
  src/utilities/logPermissionChangeByAccount.js
  src/utilities/yearMonthDayDateValidator.js
  src/websockets/TimerService/connectionsHandler.js
Labels: Do Not Review

#792 Sucheta- Refactor WeeklySummaryRecipient Button Functionality
  package-lock.json
  src/controllers/actionItemController.js
  src/controllers/badgeController.js
  src/controllers/bmdashboard/bmConsumableController.js
  src/controllers/bmdashboard/bmInventoryTypeController.js
  src/controllers/bmdashboard/bmMaterialsController.js
  src/controllers/bmdashboard/bmNewLessonController.js
  src/controllers/bmdashboard/bmProjectController.js
  src/controllers/bmdashboard/bmReusableController.js
  src/controllers/bmdashboard/bmToolController.js
  src/controllers/dashBoardController.js
  src/controllers/emailController.js
  src/controllers/informationController.js
  src/controllers/inventoryController.js
  src/controllers/mapLocationsController.js
  src/controllers/mouseoverTextController.js
  src/controllers/popupEditorBackupController.js
  src/controllers/popupEditorController.js
  src/controllers/profileInitialSetupController.js
  src/controllers/reportsController.js
  src/controllers/rolePresetsController.js
  src/controllers/rolesController.js
  src/controllers/taskController.js
  src/controllers/taskNotificationController.js
  src/controllers/teamController.js
  src/controllers/timeEntryController.js
  src/controllers/timeOffRequestController.js
  src/controllers/userProfileController.js
  src/controllers/wbsController.js
  src/helpers/dashboardhelper.js
  src/helpers/taskHelper.js
  src/helpers/userHelper.js
  src/models/emailSubcriptionList.js
  src/models/userProfile.js
  src/routes/bmdashboard/bmReusableRouter.js
  src/routes/emailRouter.js
  src/routes/userProfileRouter.js
  src/startup/db.js
  src/utilities/addMembersToTeams.js
  src/utilities/addNewField.js
  src/utilities/logPermissionChangeByAccount.js
  src/utilities/yearMonthDayDateValidator.js
  src/websockets/TimerService/connectionsHandler.js
Labels: Do Not Review

#666 Roberto fix assigning duplicate badges
  src/controllers/badgeController.js
Labels: Moved to Final Review

#800 Shengwei add Jae account edit permission
  src/controllers/logincontroller.js
Labels: Do Not Review

#801 fix blue square reason email
  src/helpers/userHelper.js
Labels: Do Not Review

#803 Diego enforcing eslint and prettier on staged files
  .eslintignore
  .eslintrc
  .husky/pre-commit
  .lintstagedrc.json
  .prettierignore
  .prettierrc
  package-lock.json
  package.json
Labels: High Priority - Please Review First

#804 Diego add conventional commits with husky
  .husky/commit-msg
  package-lock.json
Labels: High Priority - Please Review First

#805 Diego enforcing unit tests in the backend
  .eslintrc
  .lintstagedrc.json
  jest-integration.config.js
  jest-unit.config.js
  jest.config.js
  package-lock.json
  package.json
  requirements/userProfileController/postUserProfile-usercase.md
  src/controllers/userProfileController.js
  src/controllers/userProfileController.spec.js
  src/test/createTestPermissions.js
  src/test/db/createUser.js
  src/test/db/mongo-helper.js
  src/test/index.js
  src/test/mock-request.js
  src/test/mock-response.js
  src/test/mockUserProfileController.js
Labels: High Priority - Please Review First

#729 Navneeth add google doc link to weekly summaries email
  package-lock.json
  package.json
  src/helpers/userHelper.js
  src/startup/logger.js
Labels: Moved to Final Review

#813 Diego finished adding tests to postUserProfile
  package-lock.json
  package.json
  src/app.js
  src/controllers/userProfileController.js
  src/controllers/userProfileController.spec.js
  src/routes/userProfileRouter.test.js
  src/server.js
  src/test/auth/jwt.js
  src/test/db/createUser.js
  src/test/index.js
Labels: High Priority - Please Review First

#817 Abi Unit and Integration tests for getActionItem routes and Controllers
  package-lock.json
  package.json
  requirements/actionItemController/deleteactionItem.md
  requirements/actionItemController/editactionItem.md
  requirements/actionItemController/getactionItem.md
  requirements/actionItemController/postactionItem.md
  src/controllers/actionItemController.js
  src/controllers/actionItemController.spec.js
  src/controllers/timeOffRequestController.js
  src/controllers/userProfileController.js
  src/routes/actionItemRouter.test.js
  src/test/assertions.js
  src/test/db/createActionItem.js
  src/test/db/createUser.js
  src/test/index.js
  src/test/mock-request.js
Labels: High Priority - Please Review First
