Repository OneCommunityGlobal/HGNRest, pull requests merged in 2024-09, with the labels that each got.

#1082 Shadhrush - Fixing "Send Emails" visibility for Volunteers with 'Other Links' access and adding a new Send Emails Permission
  src/controllers/emailController.js
  src/test/createTestPermissions.js
  src/utilities/createInitialPermissions.js
Labels: Moved to Final Review, High Priority - Please Review First

#943 Imran split blue squares permissions
  src/controllers/userProfileController.js
  src/routes/userProfileRouter.js
  src/test/createTestPermissions.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#1077 Ivy-pwd-error-BE
  src/controllers/logincontroller.js
  src/controllers/logincontroller.spec.js
  src/controllers/userProfileController.js
Labels: High Priority - Please Review First

#1026 Logeshwari fix for user management "fetching error: invitation history"
  src/controllers/profileInitialSetupController.js
Labels: High Priority - Please Review First

#1078 Jatin create quick setup function permission
  .DS_Store
  src/controllers/titleController.js
  src/controllers/userProfileController.js
  src/routes/titleRouter.js
  src/startup/db.js
Labels: Moved to Final Review

#1097 Ivy-pause-template-hotfix
  src/controllers/userProfileController.js
  src/helpers/userHelper.js
Labels: Do Not Review, hotfix

#1094 Ivy-hotfix-email-template
  src/helpers/userHelper.js
Labels: Do Not Review

#1098 Ivy-hotfix-isSet-inactive
  src/controllers/userProfileController.js
Labels: Do Not Review, hotfix

#1102 Ivy-hotfix-isSet-twoweek-threeweek
  src/controllers/teamController.js
  src/controllers/titleController.js
  src/controllers/userProfileController.js
  src/helpers/userHelper.js
  src/models/userProfile.js
Labels: Do Not Review, hotfix

#1052 Parthj unit tests and integration test for time zone api controller.js
  package-lock.json
  requirements/timeZoneAPIController/getTImeZone.md
  requirements/timeZoneAPIController/getTimeZoneProfileInitialSetup.md
  src/controllers/timeZoneAPIController.js
  src/controllers/timeZoneAPIController.spec.js
  src/routes/timeZoneAPIRoutes.test.js
  src/startup/middleware.js
Labels: High Priority - Please Review First

#1096 Parthj unit tests task controller
  requirements/taskController/deleteTask.md
  requirements/taskController/deleteTaskByWBS.md
  requirements/taskController/fixTasks.md
  requirements/taskController/getTaskById.md
  requirements/taskController/getTasks.md
  requirements/taskController/getTasksByUserId.md
  requirements/taskController/getTasksForTeamsByUser.md
  requirements/taskController/getWBSId.md
  requirements/taskController/importTask.md
  requirements/taskController/moveTask.md
  requirements/taskController/postTask.md
  requirements/taskController/sendReviewReq.md
  requirements/taskController/swap.md
  requirements/taskController/updateAllParents.md
  requirements/taskController/updateNum.md
  requirements/taskController/updateTask.md
  requirements/taskController/updateTaskStatus.md
  src/controllers/taskController.spec.js
Labels: High Priority - Please Review First

#1103 Huijie - fix recalculation for tangible hours 2
  src/controllers/timeEntryController.js
  src/routes/timeentryRouter.js
Labels: Do Not Review

#1117 Peizhou_multiple blueSquare delete issue
  src/controllers/userProfileController.js
Labels: High Priority - Please Review First

#1083 ambika fix core team unique additions in leaderboard
  src/helpers/dashboardhelper.js
  src/helpers/userHelper.js
Labels: High Priority - Please Review First
