Repository OneCommunityGlobal/HGNRest, pull requests merged in 2025-05, with the labels that each got.

#1257 pavanswaroop-fix-member-column-filter-added-endpoint-getProjectswithActiveusers
  src/controllers/projectController.js
  src/routes/projectRouter.js
Labels: High Priority - Please Review First

#921 Luis unit test permission change logs controller
  requirements/permissionChangeLogsController/getPermissionChangeLogs.md
  src/controllers/permissionChangeLogsController.js
  src/controllers/permissionChangeLogsController.spec.js
Labels: Do Not Review

#1020 Jay Force new password for new users
  src/controllers/forcePwdController.js
Labels: Moved to Final Review

#1328 Linh - Fix gzip compression issue
  package-lock.json
  package.json
  src/app.js
  src/startup/compression.js
Labels: High Priority - Please Review First

#1270 Sharadha - Create Frontend Title search option
  src/controllers/jobsController.js
Labels: High Priority - Please Review First

#1336 Vinay: Let a user know through a popup that Permissions have been changed for them
  src/controllers/userProfileController.js
  src/models/userProfile.js
Labels: High Priority - Please Review First

#1345 Manvitha - Blue Squares not showing up
  package-lock.json
  package.json
  src/helpers/userHelper.js
Labels: High Priority - Please Review First, Urgent Priority

#1213 Haoyue faq tool implementation
  src/controllers/faqController.js
  src/models/faqs.js
  src/models/unansweredFaqs.js
  src/routes/faqRouter.js
  src/startup/routes.js
  src/utilities/createInitialPermissions.js
Labels: High Priority - Please Review First

#1279 Ziddi - Create Login Page for Listing homepage backend Listing and bidding platform - create form for new listing backend
  .DS_Store
  package-lock.json
  package.json
  src/controllers/lbdashboard/listingsController.js
  src/models/lbdashboard/listings.js
  src/routes/lbdashboard/listingsRouter.js
  src/startup/routes.js
  src/utilities/AzureBlobImages.js
Labels: High Priority - Please Review First

#1187 Sriram: added new `inventoryModifiedDatetime` field and related updates
  package-lock.json
  src/controllers/inventoryController.js
  src/controllers/inventoryController.spec.js
  src/controllers/projectController.js
  src/models/project.js
Labels: Do Not Review

#1256 Sriram optimize loading time project members
  src/controllers/projectController.js
  src/models/userProfile.js
  src/routes/projectRouter.js
Labels: High Priority - Please Review First

#1407 Rishwa - HGN Skills Dashboard: Implement UserCard design and Ranked User List
  src/controllers/hgnFormResponseController.js
  src/routes/hgnFormResponseRouter.js
Labels: High Priority - Please Review First

#1358 Sai Moola- HGN Questionnaire Dashboard: Backend: Create the Initial Help Request Modal
  src/controllers/helpCategoryController.js
  src/models/helpCategory.js
  src/routes/helpCategoryRouter.js
  src/startup/routes.js
Labels: High Priority - Please Review First

#1301 Manoj HGN Questionnaire Dashboard: Implement User Profile Page
  package-lock.json
  src/controllers/userSkillsProfileController.js
  src/models/hgnFormResponses.js
  src/routes/userSkillsProfileRouter.js
  src/startup/routes.js
Labels: High Priority - Please Review First

#1382 Lalith - HGN Questionnaire Dashboard: Backend: Implement Help Request Feedback Modal
  src/controllers/dashBoardController.js
  src/helpers/dashboardhelper.js
  src/models/userProfile.js
  src/routes/dashboardRouter.js
Labels: High Priority - Please Review First
