Repository OneCommunityGlobal/HGNRest, pull requests merged in 2025-03, with the labels that each got.

#960 Sriram taking over for Imran added requestBio permission
  src/controllers/userProfileController.js
  src/routes/userProfileRouter.js
  src/services/userService.js
  src/utilities/createInitialPermissions.js
Labels: Do Not Review, Needs New Developer

#1104 Jatin create a function to send email to user's who completed hours but missed summary
  .DS_Store
  src/cronjobs/userProfileJobs.js
  src/helpers/userHelper.js
  src/routes/userProfileRouter.js
Labels: High Priority - Please Review First

#1167 Jatin create different question sets
  src/controllers/collaborationController.js
  src/controllers/collaborationController.spec.js
  src/models/JobFormsModel.js
  src/models/jobApplicationsModel.js
  src/routes/collaborationRouter.js
  src/routes/collaborationRouter.test.js
  src/startup/routes.js
Labels: High Priority - Please Review First

#1200 Zhifan created registration api endpoints
  src/controllers/registrationController.js
  src/models/registration.js
  src/routes/registrationRouter.js
  src/startup/routes.js
Labels: High Priority - Please Review First

#1252 Jaissica - added array of reasons to infringements
  src/controllers/userProfileController.js
  src/helpers/userHelper.js
  src/models/userProfile.js
Labels: High Priority - Please Review First

#1277 jatin - BLUE SQUARE AUTORESPONDER - fix the missed summary email
  src/cronjobs/userProfileJobs.js
  src/helpers/userHelper.js
Labels: High Priority - Please Review First, Urgent Priority

#1287 Dipti- Fix Timelog Times Not Totaling Task-Time-Worked on Dashboard>Tasks Tab
  src/controllers/timeEntryController.js
Labels: High Priority - Please Review First

#1254 fix: handled empty permission additions or removal
  src/controllers/permissionChangeLogsController.js
  src/utilities/logUserPermissionChangeByAccount.js
Labels: High Priority - Please Review First

#1298 Dipti_Yadav_Make_WBS_content_save_and_auto-populate_during_auto-refresh_popup
  src/controllers/taskController.js
Labels: High Priority - Please Review First
